### ISSUE TITLE
Application pour OS Linux

### ISSUE THREAD

**Issue by RomainLLC** [UpSignOn/UpSignOn-pro-server#8]
Bonjour,

est-il prévu à terme une application Linux?

Certains sysadmins ou certains secteurs (ex: pôle universitaires) sont full Linux et ne peuvent utiliser le client.

Merci !

**Comment by giregk** [comment]
Bonjour Romain, oui, la refonte de l'application est en cours et elle apportera la compatibilité de l'application pour Linux. Livraison prévu pour linux prévue en mai ou juin.

**Comment by giregk** [comment]
Bonjour @RomainLLC, UpSignOn est enfin disponible sur Linux. Il reste quelques sujets mineurs à traiter, mais vous pouvez déjà commencer à l'utiliser. Plus d'informations sur cette page: https://upsignon.notion.site/Liens-de-t-l-chargement-de-l-application-45c3531505d4438d86a67890296ae437?pvs=4
